RegisterLLAT/WebApp/Models/Register.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebApp.AppTools;

namespace WebApp.Models
{
	public class Register
	{
		[Key]
		public int Id { get; set; }

		public DateTime TimeIn { get; set; }

		public DateTime? TimeOut { get; set; }

		public string Mistake { get; set; }

		public int PersonId { get; set; }

		public string LName { get; set; }

		public string FName { get; set; }

		public string CompanyName { get; set; }

		public string StatusName { get; set; }

		public int? PersonVisited { get; set; }

		public string VisitedLName { get; set; }

		public string VisitedFName { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterPlanningViewModels/SetCompany.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace WebApp.Models.RegisterPlanningViewModels
{
	public class SetCompany 
	{
		public int MyProperty { get ; set ; }
	}
}

RegisterLLAT/WebApp/Models/RegisterPlanningViewModels/SetStatus.cs
using DAL.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using WebApp.AppTools;

namespace WebApp.Models.RegisterPlanningViewModels
{
	public class SetStatus
	{
		[Key]
		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }

		private IEnumerable<CompanyStatus> _companyStatuses;

		public IEnumerable<CompanyStatus> CompanyStatus
		{
			get 
			{
				if (_companyStatuses == null)
				{
					CompanyStatusService service = new CompanyStatusService();
					_companyStatuses = service.GetAll().Select(cs => cs.DalToCompanyStatusApp());
				}
				return _companyStatuses; 
			}
			set { _companyStatuses = value; }
		}

		// public IEnumerable<CompanyStatus> CompanyStatus { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetCompany.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using WebApp.AppTools.Attributes;

namespace WebApp.Models.RegisterViewModels
{
	public class SetCompany
	{
		[Key]
		[Display(Name = "Nom de la société")]
		[EmptyOrPositive(ErrorMessage = "Ce champ doit être un nombre positif ou sans valeur")]
		public int? Id { get; set; }

		public List<SelectListItem> Options { get; set; } // TODO : potential useless

		public List<Company> Companies { get; set; }

		[Display(Name = "Indiquez le nom de la société")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le nom de la société est requis")]
		public string Name { get; set; }

		public int IdAutoComplete { get; set; }

		[Display(Name = "Département")]
		[EmptyOrPositive(ErrorMessage = "Ce champ doit être un nombre positif ou sans valeur")]
		public int? DepartmentId { get; set; } // TODO : potential useless

		public List<Department> Departments { get; set; } 

		[Display(Name = "Nom du département")]
		[RequiredIfOtherFieldIsZero("DepartmentId", ErrorMessage = "Le nom du département est requis")]
		public string DepartmentName { get; set; } // TODO : potential useless

		public int CompanyStatusId { get; set; } // TODO : potential useless
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetPerson.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebApp.AppTools.Attributes;

namespace WebApp.Models.RegisterViewModels
{
	public class SetPerson
	{
		[Key]
		[Display(Name = "Vos nom et prénom")]
		public int? Id { get; set; }

		public List<SelectListItem> OptionsPersons { get; set; }

		public List<PersonListVM> Persons { get; set; }

		[Display(Name = "Nom de famille")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le nom de famille est requis")]
		public string LName { get; set; }

		[Display(Name = "Prénom")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le prénom est requis")]
		public string FName { get; set; }

		public DateTime? DateBegin { get; set; }

		public DateTime? DateEnd { get; set; }

		[Display(Name = "Personne visitée")]
		public int? PersonVisitedId { get; set; }

		public List<SelectListItem> OptionsPVisited { get; set; }

		public List<PersonListVM> PersonsVisited { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetStatus.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace WebApp.Models.RegisterViewModels
{
	public class SetStatus
	{
		[Key]
		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }

		public IEnumerable<CompanyStatus> CompanyStatus { get; set; }
	}
}

RegisterLLAT/WebApp/Controllers/CheckInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Services;
using DALE = DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using WebApp.AppTools;
using WebApp.Models.CheckInViewModels;
using WebApp.Models.RegisterViewModels;
using WebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace WebApp.Controllers
{
    [AllowAnonymous]
	public class CheckInController : Controller
	{
        [HttpGet]
        public IActionResult RegisterType()
		{
			return View("RegisterType");
		}

        [HttpPost]
        public IActionResult RegisterType(bool isCheckingOut)
        {
            User user = GetUser();
            user.isCheckinOut = isCheckingOut;
            HttpContext.Session.SetComplexData("user", user);

            // Set Model with new value
            //CheckInVM register = new CheckInVM();
            //register.IsCheckingOut = isCheckingOut;

            return RedirectToAction("SetStatus");
        }

        [HttpGet]
        public IActionResult SetStatus()
        {
            CheckInVM register = new CheckInVM();
            return View("SetStatus", register);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SetStatus(CheckInVM register)
        {
            User user = GetUser();
            
            // In case of next/previous check that status has not changed
            if (user.StatusId > 0 && user.StatusId != register.StatusId)
			{
                ResetUser(user);
			}

            // Check whether the status exist in the DB
            ViewBag.Error = ControllerMethods.CheckCompanyStatus(register.StatusId);
            if (ViewBag.Error != null)
            {
                return View("SetStatus", register);
            }

            // Save valid statusId in session
            user.StatusId = register.StatusId;
			if (user.StatusId == 1)
			{
                user.CompanyId = 1;
			}
            HttpContext.Session.SetComplexData("user", user);

            return RedirectToAction("SetCompany");
        }

        [HttpGet]
        public IActionResult SetCompany()
        {
            User user = GetUser();

            // extract to method
            CheckInVM register = new CheckInVM();
            register.IsCheckingOut = user.isCheckinOut;
            register.StatusId = user.StatusId;
            register.DepartmentId = user.DepartmentId;
            register.DepartmentName = user.DepartmentName;
            register.CompanyId = user.CompanyId;
            register.CompanyName = user.CompanyName;

            // If status is "Intern"
            if (register.StatusId == 1)
            {
                register.Companies = null;
                register.CompanyId = 1;

                // Get SNCB's departments
                register.Departments = GetDepartmentsForDropDown((int)register.CompanyId);

                if (register.Departments.Count() == 0)
                {
                    register.DepartmentId = 0;
                }
            }
            else
            {
                // Get companies by status 
                register.Companies = GetCompaniesForDropDown(register.StatusId);

                // Provide the company's dropdownlist
                if (register.Companies.Count() == 0)
                {
                    register.CompanyId = 0;
                }
            }
            return View("SetCompany", register);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SetCompany(CheckInVM register, string nextBtn, string prevBtn)
        {
            User user = GetUser();

            if (prevBtn != null)
            {
                return RedirectToAction("SetStatus");
            }

            if (ModelState.IsValid)
            {
                if (nextBtn != null)
                {
                    // Server Side validation
                    ViewBag.Error = null;

                    // Get the statusId from session (just in case)                    
                    register.StatusId = user.StatusId;

                    if (register.StatusId == 1)
                    {
                        ViewBag.Error = SetCompanyCheckDepartment(register, user);
                    }
                    else if (register.StatusId > 1 && register.StatusId <= 3)
                    {
                        ViewBag.Error = SetCompanyCheckCompany(register, user);                       
                    }
					else
					{
                        ViewBag.Error = "Cette société n'est pas valide.";
					}
                }

                // Server side valtion error, return to view
                if (ViewBag.Error != null)
                {
                    register = ReturnSetCompanyToView(register);
                    return View("SetCompany", register);
                }
            }
			else
			{
                register = ReturnSetCompanyToView(register);
                return View("SetCompany", register);
            }

            // Save session
            HttpContext.Session.SetComplexData("user", user);

            return RedirectToAction("SetPerson");
        }

		[HttpGet]
        public IActionResult SetPerson()
        {
            User user = GetUser();
            CheckInVM register = new CheckInVM();
            register.IsCheckingOut = user.isCheckinOut;
            register.StatusId = user.StatusId;
            register.CompanyId = user.CompanyId;
            register.DepartmentId = user.DepartmentId;

            PersonService service = new PersonService();

			// The user is an intern (SNCB)
			if (register.StatusId == 1)
			{
                register.Persons = GetPersonsForDropDown(register);
            }
			else if (register.StatusId > 1 && register.StatusId <= 3)
			{
                register.Persons = GetPersonsForDropDown(register);
            }

            // Add "Autre" selected item if the list exist
            if (register.Persons.Count() > 0)
            {
                register.Persons.Insert(0, new PersonListVM { Id = 0, FName = null, LName = null });
            }
			else
			{
                register.PersonId = 0;
            }

            // Prepare dropdown for the visitee if the person is not an intern (SNCB Atelier d'Arlon)
            if (register.DepartmentId != 2)
			{
                register.PersonsVisited = GetPersonsForVisiteeDropDown(register);

                if (register.PersonsVisited.Count() > 0) 
                {
                    register.PersonsVisited.Insert(0, new PersonListVM { Id = 0, FName = "", LName = "" });
                }
				else
				{
                    register.PersonVisitedId = 0;
                } 
            }
			else
			{
                register.PersonsVisited = null;
			}

            return View("SetPerson", register);
        }

        [HttpPost]
        public IActionResult SetPerson(CheckInVM register, string prevBtn)
        {
			if (prevBtn != null)
			{
                return RedirectToAction("SetCompany");
            }

            User user = GetUser();

            // Get the statusId from session (just in case) + CompanyId                
            register.StatusId = user.StatusId;
            register.CompanyId = user.CompanyId;
            register.DepartmentId = user.DepartmentId;

            if (!ModelState.IsValid)
			{
                register = ReturnSetPersonToView(register);
                return View("SetPerson", register);
            }

            ViewBag.Error = null;
            ViewBag.NameError = null;
            ViewBag.VisitedError = null;

            // Check provided person
            PersonService service = new PersonService();

			if (register.PersonId > 0)
			{
                DALE.Person person = null; 

                if (register.StatusId == 1)
				{
                    person = service.Get((int)register.PersonId, (int)register.CompanyId, (int)register.DepartmentId);
                }
				else
				{
                    person = service.Get((int)register.PersonId, (int)register.CompanyId);
                }                

				if (person == null)
				{
                    ViewBag.Error = "Cette personne n'existe pas. Veuillez choisir une personne de la liste ou l'ajouter en cliquant sur \"Autre\"";
                }
			}
			else if (register.PersonId == 0)
			{
                // TODO : Loris
                if (String.IsNullOrWhiteSpace(register.FName) | String.IsNullOrWhiteSpace(register.LName))
				{
                    ViewBag.NameError = "Veuillez indiquer vos nom et prénom.";
                }
				else
				{
                    // Check that the person is not already in DB
                    DALE.Person checkPerson = null;

					if (register.StatusId == 1)
					{
                        // TODO : Loris
                        checkPerson = service.GetAll(register.LName, register.FName)
                            .Where(p => p.CompanyId == (int)register.CompanyId && p.DepartmentId == (int)register.DepartmentId)
                            .SingleOrDefault();
                    }
					else
					{
                        // TODO : Loris
                        checkPerson = service.GetAll(register.LName, register.FName)
                            .Where(p => p.CompanyId == (int)register.CompanyId)
                            .SingleOrDefault();
                    }

					if (checkPerson != null)
					{
                        ViewBag.NameError = "Une personne avec les mêmes nom et prénom existe déjà. Veuillez vous différencier (ex: deuxième nom de famille).";
                    }
				}
			}
			else
			{

RegisterLLAT/WebApp/Views/CheckIn/RegisterSummary.cshtml
@model WebApp.Models.RegisterViewModels.RegisterVM

@{
    ViewData["Title"] = "RegisterSummary";
}

<h1>Registre des présences</h1>
<h2>Enregistrement terminé</h2>
<hr />

<p>Merci d'avoir signé le registre.</p>

@if (ViewBag.IsCheckInOut == false)
{
    <p>N'oubliez pas de signer à nouveau lors de votre sortie.</p>
}
else
{
    if (ViewBag.Mistake != null)
    {
        <p>Nous constatons que vous avez oublié de vous enregistrer à votre arrivée. Soyez attentif-ve lors de votre prochaine visite.</p>
    }
}

@if (ViewBag.TestActive == true)
{
    <p>Nous souhaiterions à présent vérifier votre maîtrise des règles de sécurité.</p>
    <p>Merci de cliquer sur "Passer le test".</p>
    <input type="button" asp-action="SecurityTest" formmethod="get" value="Passer le test" />
}
else
{
    <input type="button" asp-controller="Home" asp-action="Index" formmethod="get" value="Terminer" />
}






RegisterLLAT/WebApp/Views/CheckIn/RegisterType.cshtml

@{
    ViewData["Title"] = "Index";
}

<h1>Registre des présences</h1>
<h2>Enregistrement</h2>
<hr />
<p>A votre arrivée sur le site, cliquez sur "Signaler son arrivée". A la sortie, n'oubliez pas de signer en cliquant sur "Signaler son départ."</p>

<p>Si vous quittez le site et que vous avez oublié de signer à votre arrivée, cliquez sur "Signalez son départ".</p>

<form class="d-inline-block" action="RegisterType" method="post">
    <input type="hidden" name="isCheckingOut" value="false" />
    <input class="btn btn-primary" type="submit" value="Signaler son arrivée" />
</form>

<form class="d-inline-block" action="RegisterType" method="post">
    <input type="hidden" name="isCheckingOut" value="true" />
    <input class="btn btn-primary" type="submit" value="Signaler son départ" />
</form>

RegisterLLAT/WebApp/Views/CheckIn/SetCompany.cshtml
@model WebApp.Models.CheckInViewModels.CheckInVM

@{
    ViewData["Title"] = "SetCompany";
}

<h1>Registre des présences</h1>
@if (Model.IsCheckingOut == true)
{
    <h2>Enregistrement: check-out</h2>
}
else
{
    <h2>Enregistrement: check-in</h2>
}
<hr />

@if (Model.StatusId == 1)
{
    <h3>Dans quel département de la SNCB travaillez-vous?</h3>
}
else
{
    <h3>Pour quelle société travaillez-vous?</h3>
}

<div class="row">
    <div class="col-md-8">
        <form asp-action="SetCompany" method="post" id="formSetCompany">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="IdAutoComplete" />
            <input type="hidden" asp-for="StatusId" />

            @if (Model.StatusId == 1)
            {
                @* Give companyId the value "1" which is the SNCB Id *@
                <input type="hidden" asp-for="CompanyId" value=@Model.CompanyId />

                @*DropDown List for department*@
                <div class="form-group" id="setCompanyDepartment">
                    <label asp-for="DepartmentId" class="control-label"></label>
                    <select asp-items="@(new SelectList(Model.Departments, "Id", "Name", Model.DepartmentId))" asp-for="DepartmentId">
                        <option value="">-- Sélectionnez un département --</option>
                    </select>
                    <span asp-validation-for="DepartmentId" class="text-danger"></span>
                </div>

                @*Input text for company's other name*@
                <div class="form-group d-none" id="setCompanyNameOther">
                    <label asp-for="CompanyName" class="control-label"></label>
                    <input asp-for="CompanyName" class="form-control" value=@Model.CompanyName/>
                    <div asp-validation-for="CompanyName" class="text-danger"></div>
                </div>

                @*Input text for department's other name*@
                <div class="form-group d-none" id="setDepartmentNameOther">
                    <label asp-for="DepartmentName" class="control-label"></label>
                    <input asp-for="DepartmentName" class="form-control" value=@Model.DepartmentName/>
                    <span asp-validation-for="DepartmentName" class="text-danger"></span>
                </div>
            }
            else
            {
                if (Model.Companies.Count() > 0)
                {
                    // DropDown List for company
                    <div class="form-group" id="setCompanyId">
                        <label asp-for="CompanyId" class="control-label"></label>
                        <select asp-items="@(new SelectList(Model.Companies, "Id", "CompanyName", Model.CompanyId))" asp-for="CompanyId">
                            <option value="">-- Sélectionnez une société --</option>
                        </select>
                        <span asp-validation-for="CompanyId" class="text-danger"></span>
                    </div>
                }
                else
                {
                    // Display field for companyId
                    <input type="hidden" asp-for="CompanyId" value="CompanyId" />
                }

                // Input text for company's other name
                <div class="form-group d-none" id="setCompanyNameOther">
                    <label asp-for="CompanyName" class="control-label"></label>
                    <input asp-for="CompanyName" class="form-control" />
                    <span asp-validation-for="CompanyName" class="text-danger" value=@Model.CompanyName></span>
                </div>
            }

            @if (ViewBag.Error != null)
            {
                <div id="viewBagError">
                    <p class="text-danger">Une erreur est survenue : @ViewBag.Error</p>
                </div>
            }

            <div class="form-group">
                <input type="submit" name="prevBtn" value="Précédant" class="btn btn-primary" />
                <input type="submit" name="nextBtn" value="Suivant" class="btn btn-primary" />
            </div>
        </form>

        @*@if (ViewBag.Error != null)
        {
            <div id="viewBagError">
                <p class="text-danger">Une erreur est survenue : @ViewBag.Error</p>
            </div>
        }*@

    </div>
</div>


@section Scripts {
    <script>

        // Save selectors and html blocks
        let departmentDDBlock = $("#setCompanyDepartment");
        let departmentDDContent = $("#DepartmentId").html();
        let companyOtherName = $("#setCompanyNameOther");
        let departmentOtherName = $("#setDepartmentNameOther");

        // Store the Id value of the selected department item before it s remove from the DOM
        let dropdwDepartmentId = $("select#DepartmentId");
        let departmentId = dropdwDepartmentId.val();

        $(document).ready(function () {

            // Error postback view handeling
            if ($("#viewBagError").length) {

                // Remove dropdown selected values if present from Error postback
                if ($("#CompanyId option:selected").length) {
                    $("#CompanyId option:selected").removeAttr('selected')
                }

                if ($("#DepartmentId option:selected").length) {
                    $("#DepartmentId option:selected").removeAttr('selected')
                }

                //FadeOut ViewBag
                fadeOutCustom($("#viewBagError"), 13000);
            }

            //// FadeOut Jquery validation error message
            //if ($(".field-validation-error").length) {
            //    console.log("passe");
            //    fadeOutCustom($(".field-validation-error > span"), 10000)
            //}

            let statusIdVal = $("#StatusId").val();

            // If the user is an intern (SNCB employee)
            if (statusIdVal == 1) {

                // In case the user clicked "previous/next", clear previous values
                if ($("#CompanyName").val() != "") {
                    $("#CompanyName").val("");
                    console.log("passe");
                    companyOtherName.addClass('d-none');
                }

                if (departmentDDBlock.hasClass("d-none")) {
                    departmentDDBlock.removeClass('d-none');
                }

                // Toggle input text for department on dropdown change
                $("select#DepartmentId").change(function () {
                    departmentId = dropdwDepartmentId.val();

                    if ($("#DepartmentName").val() != null) {
                        $("#DepartmentName").val("");
                    }

                    if (departmentId === "0") {
                        departmentOtherName.removeClass('d-none');
                    }
                    else {
                        departmentOtherName.addClass('d-none');
                    }
                });
            }
            else if (statusIdVal > 1 && statusIdVal <= 3) {

                // In case the user clicked "previous/next", clear previous values
                if ($("#DepartmentName").val() != "") {
                    $("#DepartmentName").val("");
                    departmentOtherName.addClass('d-none');
                }

                // Store the Id value of the selected company item
                let dropdwId = $("select#CompanyId");
                let id = dropdwId.val();

                // When a selection is made by the user in the company dropdownlist
                $(dropdwId).change(function () {

                    // Remove selected if present from postback Error
                    if ($("#CompanyId option:selected").length) {
                        $("#CompanyId option").removeAttr('selected')
                    }

                    // Remove input field for company's name
                    //$("#Name").autocomplete('close').val('');
                    if ($("#CompanyName").val() != null) {
                        $("#CompanyName").val("");
                    }

                    // Modify the Id value of the selected item
                    id = dropdwId.val();

                    // If the user selects a company >
                    if (id > "0") {

                        if (!companyOtherName.hasClass("d-none")) {
                            companyOtherName.addClass('d-none');
                        }
                    }
                    // If the user selects "Autre"
                    else if (id === "0") {

                        // Display Company Other Name Field
                        if (companyOtherName.hasClass("d-none")) {
                            companyOtherName.removeClass('d-none');
                        }
                    }
                    // If the user selects the default value : reset everything
                    else {
                        // Hide Departement Other Name Field
                        if (!companyOtherName.hasClass("d-none")) {
                            companyOtherName.addClass('d-none');
                        }
                    }
                });
            }

            // Remove input field for company's name
            //$("#Name").autocomplete('close').val('');
            //if ($("#CompanyName").val() != null) {
            //    $("#CompanyName").val("");
            //}

            // AutoComplete for the company name
            // Suggestions will allow the user to potentially chose an existing company
            // If the user makes a choice, the Id of the company and the companyStatus will be inserted in hidden input fields
            // The persistence logic will reside in the controller
            $("#CompanyName").autocomplete({
                minLength: 3,
                source: function (request, response) {
                    $.ajax({
                        url: "/Register/AutoComplete",
                        type: "POST",
                        dataType: "json",
                        data: { Prefix: request.term.toLowerCase() },
                        success: function (data) {

                            var array = data.error ? [] : $.map(data, function (m) {
                                return {
                                    label: m.companyName,
                                    value: m.id,
                                    status: m.companyStatusId,
                                };
                            });
                            response(array);
                        },
                    });
                },
                select: function (event, ui) {
                    $("#CompanyName").val(ui.item.label);
                    $("#IdAutoComplete").val(ui.item.value);
                    $("#StatusId").val(ui.item.status);
                    return false;
                }
            })
        }); // End of document
    </script>
}


RegisterLLAT/WebApp/Views/CheckIn/SetStatus.cshtml
@model WebApp.Models.CheckInViewModels.CheckInVM

@{
    ViewData["Title"] = "SetStatus";
}

<h1>Registre des présences</h1>
@if (Model.IsCheckingOut == true)
{
    <h2>Enregistrement: check-out</h2>
}
else
{
    <h2>Enregistrement: check-in</h2>
}
<hr />

<h3>Quel est votre statut?</h3>

<div class="adapt75">
    <p>En principe, votre statut vous a été fourni par l'Atelier d'Arlon avant votre visite.</p>

    <p>
        - Interne correspond aux employés des différents ateliers de maintenance de la SNCB.<br />
        - Prestataire externe correspond aux employés des sous-traitants de l'Atelier d'Arlon.<br />
        - Visiteur correspond aux écoles, stagiaires, etc.
    </p>

    <p>En cas de doute, faites un choix. Si la société ou entité de laquelle vous dépendez n'est pas reprise dans les listes de pages suivantes, vous pourrez revenir en arrière et modifier votre statut.</p>
</div>

@using (Html.BeginForm("SetStatus", "CheckIn", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-6">
            <form asp-action="SetStatus">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" id="userCompanyStatus" asp-for="StatusId" />

                @foreach (var item in Model.CompanyStatuses)
                {
                    <input type="submit" value="@item.StatusName" class="btn btn-primary" id="@item.Id" />
                }
            </form>
        </div>
    </div>
}

@if (ViewBag.Error != null)
{
    <div>
        <p class="text-danger">Une erreur est survenue : @ViewBag.Error</p>
    </div>
}
@section Scripts {
    <script>
        $(document).ready(function () {

            $(":submit").click(function (e) {

                // Get Id value of clicked input
                var clickedInputId = $(this).attr('id');

                // Set Id field value
                $("#userCompanyStatus").val(clickedInputId)
            })
        });
    </script>
}