RegisterLLAT/WebApp/Models/RegisterPlanning.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
	public class RegisterPlanning 
	{
		[Key]
		public int Id { get; set; }

		public DateTime TimeIn { get; set; }

		public DateTime? TimeOut { get; set; }

		public string Mistake { get; set; }

		public string State { get; set; }

		public bool Planned { get; set; }

		public int PersonId { get; set; }

		public string LName { get; set; }

		public string FName { get; set; }

		public int CompanyId { get; set; }

		public string CompanyName { get; set; }

		public string StatusName { get; set; }

		public int? PersonVisited { get; set; }

		public string VisitedLName { get; set; }

		public string VisitedFName { get; set; }

		public int AdministratorId { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterPlanningViewModels/SetCompany.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace WebApp.Models.RegisterPlanningViewModels
{
	public class SetCompany 
	{
		public int MyProperty { get ; set ; }
	}
}

RegisterLLAT/WebApp/Models/RegisterPlanningViewModels/SetStatus.cs
using DAL.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using WebApp.AppTools;

namespace WebApp.Models.RegisterPlanningViewModels
{
	public class SetStatus
	{
		[Key]
		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }

		private IEnumerable<CompanyStatus> _companyStatuses;

		public IEnumerable<CompanyStatus> CompanyStatus
		{
			get 
			{
				if (_companyStatuses == null)
				{
					CompanyStatusService service = new CompanyStatusService();
					_companyStatuses = service.GetAll().Select(cs => cs.DalToCompanyStatusApp());
				}
				return _companyStatuses; 
			}
			set { _companyStatuses = value; }
		}

		// public IEnumerable<CompanyStatus> CompanyStatus { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterPlanningViewModels/SetTime.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models.RegisterPlanningViewModels
{
	public class SetTime
	{
		public string SameDayDate { get; set; }

		public string SameDayTimeIn { get; set; }

		public string SameDayTimeOut { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetCompany.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using WebApp.AppTools.Attributes;

namespace WebApp.Models.RegisterViewModels
{
	public class SetCompany
	{
		[Key]
		[Display(Name = "Nom de la société")]
		[EmptyOrPositive(ErrorMessage = "Ce champ doit être un nombre positif ou sans valeur")]
		public int? Id { get; set; }

		public List<SelectListItem> Options { get; set; } // TODO : potential useless

		public List<Company> Companies { get; set; }

		[Display(Name = "Indiquez le nom de la société")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le nom de la société est requis")]
		public string Name { get; set; }

		public int IdAutoComplete { get; set; }

		[Display(Name = "Département")]
		[EmptyOrPositive(ErrorMessage = "Ce champ doit être un nombre positif ou sans valeur")]
		public int? DepartmentId { get; set; } // TODO : potential useless

		public List<Department> Departments { get; set; } 

		[Display(Name = "Nom du département")]
		[RequiredIfOtherFieldIsZero("DepartmentId", ErrorMessage = "Le nom du département est requis")]
		public string DepartmentName { get; set; } // TODO : potential useless

		public int CompanyStatusId { get; set; } // TODO : potential useless
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetPerson.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebApp.AppTools.Attributes;

namespace WebApp.Models.RegisterViewModels
{
	public class SetPerson
	{
		[Key]
		[Display(Name = "Vos nom et prénom")]
		public int? Id { get; set; }

		public List<SelectListItem> OptionsPersons { get; set; }

		public List<PersonListVM> Persons { get; set; }

		[Display(Name = "Nom de famille")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le nom de famille est requis")]
		public string LName { get; set; }

		[Display(Name = "Prénom")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le prénom est requis")]
		public string FName { get; set; }

		public DateTime? DateBegin { get; set; }

		public DateTime? DateEnd { get; set; }

		[Display(Name = "Personne visitée")]
		public int? PersonVisitedId { get; set; }

		public List<SelectListItem> OptionsPVisited { get; set; }

		public List<PersonListVM> PersonsVisited { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetStatus.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace WebApp.Models.RegisterViewModels
{
	public class SetStatus
	{
		[Key]
		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }

		public IEnumerable<CompanyStatus> CompanyStatus { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetTime.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models.RegisterViewModels
{
	public class SetTime
	{
		public int PlanningTypeId { get; set; } = 0;
		
		public List<PlanningType> Planning = new List<PlanningType>()
		{
			new PlanningType { Id = 1, Type = "un jour" },
			new PlanningType { Id = 2, Type = "une période même horaire" },
			new PlanningType { Id = 3, Type = "personnalisé" },
		};

		public string SameDayDate { get; set; }

		public string SameDayTimeIn { get; set; }

		public string SameDayTimeOut { get; set; }

		public string DifferentDayTimeIn { get; set; }

		public string DifferentDayTimeOut { get; set; }

		public class PlanningType
		{
			public int Id { get; set; }

			public string Type { get; set; }
		}
	}


}

RegisterLLAT/WebApp/Models/Test.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
	public class Test
	{
		public int Id { get; set; }

		public string Title { get; set; }

		public string VideoURL { get; set; }

		public bool IsActive { get; set; }

		public int TestSettingsId { get; set; }

		public string TestSettingsTitle { get; set; }
	}
}

RegisterLLAT/WebApp/Controllers/RegisterPlanningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Services;
using DALE = DAL.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp.AppTools;
using WebApp.Facades.Register;
using WebApp.Models;
using WebApp.Models.RegisterPlanningViewModels;
using Microsoft.AspNetCore.Authorization;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Super Admin, Full Admin, HR Admin")]
    public class RegisterPlanningController : Controller
	{
		//public IActionResult Index()
		//{
		//	return View();
		//}

        [HttpGet]
        public IActionResult SetStatus()
        {
            //User user = GetUser();

            FormRegisterPlanningVM register = new FormRegisterPlanningVM();

            //SetStatus status = new SetStatus();
            //CompanyStatusService serv = new CompanyStatusService();
            //status.CompanyStatus = serv.GetAll().Select(cs => cs.DalToCompanyStatusApp()).ToList();

            // Save statuses
            //statusesGlobal = status.CompanyStatus;
            
            // If next && previous
            //status.Id = user.StatusId;

            return View(register);
        }

        [HttpPost]
		public IActionResult SetStatus(string nextBtn, FormRegisterPlanningVM register)
		{
			User session = GetUser();

			if (nextBtn != null)
			{
                // Check if a choice is made, if so check that the status exists
				ViewBag.Error = ControllerMethods.CheckCompanyStatus(register.Id);
				if (ViewBag.Error != null)
				{
                    return View(register);
                }

                // if status is valid
                session.StatusId = register.Id;
				HttpContext.Session.SetComplexData("user", session);

				return RedirectToAction("SetCompany");

			}
			return View(register);
		}

        //[HttpGet]
        //public IActionResult SetCompany()
        //{
        //    User user = GetUser();

        //    RegisterFacade facade = new RegisterFacade();

        //    SetCompany company = facade.SessionToSetCompany(user);
        //    company = facade.PrepareCompany(company);

        //    return View(company);
        //}

        [HttpGet]
        public IActionResult SetCompany()
        {
            User user = GetUser();

            FormRegisterPlanningVM register = new FormRegisterPlanningVM();
            register = register.UserToSetCompanyProps(user);

            register = register.SetCompany(register);

            return View(register);
        }

        //[HttpPost]
        //public IActionResult AddRegisterPlanningCompany(string nextBtn, string prevBtn, SetCompany company)
        //{
        //    User user = GetUser();
        //    RegisterFacade facade = new RegisterFacade();

        //    if (prevBtn != null)
        //    {
        //        return RedirectToAction("SetStatus");
        //    }

        //    if (nextBtn != null)
        //    {
        //        // Client side validation
        //        if (!ModelState.IsValid)
        //        {
        //            company = facade.PrepareCompany(company);
        //            return View(company);
        //        }
        //        // Server side validation
        //        else
        //        {
        //            ViewBag.Error = facade.CheckCompany(company);
        //        }
        //    }

        //    // An error occured, return to view
        //    if (ViewBag.Error != null)
        //    {
        //        company = facade.PrepareCompany(company);
        //        return View(company);
        //    }
        //    else
        //    {
        //        // No error save new company and new department if exists
        //        if (company.Name != null)
        //            user.CompanyId = facade.SaveCompany(company);
        //        user.CompanyId = (int)company.Id;

        //        if (company.DepartmentName != null)
        //            user.DepartmentId = facade.SaveDepartment(company);
        //        user.DepartmentId = company.DepartmentId;
        //    }

        //    // Save session
        //    HttpContext.Session.SetComplexData("user", user);

        //    return RedirectToAction("AddRegisterPlanningPerson");
        //}

        //[HttpGet]
        //public IActionResult AddRegisterPlanningPerson()
        //{
        //    User user = GetUser();
        //    SetPerson person = SetPersonToView(user);
        //    return View(person);
        //}

        //[HttpPost]
        //public IActionResult AddRegisterPlanningPerson(string nextBtn, string prevBtn, SetPerson person)
        //{
        //    User user = GetUser();

        //    PersonService serv = new PersonService();

        //    if (prevBtn != null)
        //    {
        //        return RedirectToAction("AddRegisterPlanningCompany");
        //    }

        //    if (nextBtn != null)
        //    {
        //        if (!ModelState.IsValid)
        //        {
        //            SetPerson personToView = SetPersonToView(user);
        //            return View(personToView);
        //        }
        //        else
        //        {
        //            // A user is selected from the list
        //            if (person.Id > 0)
        //            {
        //                // Check that the person is in DB
        //                DALE.Person personExist = serv.Get((int)person.Id, (int)user.CompanyId);

        //                if (personExist != null)
        //                {
        //                    user.Id = (int)person.Id;
        //                }
        //                else
        //                {
        //                    ViewBag.Error = "Cette personne n'existe pas";
        //                }
        //            }
        //            else if (person.Id == 0)
        //            {
        //                string nameAndLastName = ControllerMethods.NameAndLastNameValid(person.FName, person.LName);

        //                if (nameAndLastName == null)
        //                {
        //                    // Prevent duplicate in the DB, search by LName & FName or FName & LName
        //                    Person personExists = CheckIfPersonExistInACompany(user, person);

        //                    // If we find a duplicate alert the user
        //                    if (personExists != null)
        //                    {
        //                        ViewBag.NameError = "Cette personne existe déjà, sélectionnez la dans la liste. Si vous souhaitez ajouter une personne portant le même nom et le même prénom, ajoutez une différenciation (ex: troisième prénom).";
        //                    }
        //                    else
        //                    {
        //                        user.Id = 0;
        //                        user.LName = person.LName;
        //                        user.FName = person.FName;
        //                    }
        //                }
        //                // In case of error, set viewbag
        //                else
        //                {
        //                    ViewBag.NameError = nameAndLastName;
        //                }
        //            }
        //            else
        //            {
        //                ViewBag.Error = "Veuillez choisir une personne dans la liste ou inscrire son nom manuellement";
        //            }

        //            // The user is a visitor and must provide a visitee
        //            if (user.StatusId == 3)
        //            {
        //                if (person.PersonVisitedId > 0)
        //                {
        //                    // Check that the visitee is in DB
        //                    DALE.Person personVisitedExists = serv.GetPersonVisited((int)person.PersonVisitedId);

        //                    if (personVisitedExists != null)
        //                    {
        //                        user.PersonVisited = person.PersonVisitedId;
        //                    }
        //                    else
        //                    {
        //                        ViewBag.VisitedError = "La personne visitée n'existe pas.";
        //                    }
        //                }
        //                else
        //                {
        //                    ViewBag.VisitedError = "Veuillez sélectionner la personne que vous venez visiter.";
        //                }
        //            }
        //        }
        //    }

        //    if (ViewBag.Error != null || ViewBag.NameError != null || ViewBag.VisitedError != null)
        //    {
        //        SetPerson personToView = SetPersonToView(user);
        //        return View(personToView);
        //    }
        //    else
        //    {
        //        // Save new user if he/she exists
        //        if (user.LName != null && user.FName != null)
        //        {
        //            DALE.Person newPerson = new DALE.Person();
        //            newPerson.LName = user.LName;
        //            newPerson.FName = user.FName;
        //            newPerson.AdministratorId = 1;
        //            newPerson.CompanyId = (int)user.CompanyId;
        //            newPerson.DepartmentId = user.DepartmentId;
        //            newPerson.Id = serv.Insert(newPerson);
        //            user.Id = newPerson.Id;

        //            // reset values as a new user was created
        //            user.FName = null;
        //            user.LName = null;
        //        }

        //        // Save session
        //        HttpContext.Session.SetComplexData("user", user);


RegisterLLAT/WebApp/Views/RegisterPlanning/GetRegisters.cshtml

@using RegisterPlanningVM = WebApp.Models.RegisterPlanningViewModels.RegisterPlanningVM
@model IEnumerable<WebApp.Models.RegisterPlanningViewModels.RegisterPlanningVM>

@{
    ViewData["Title"] = "GetRegisters";
}

<h1>Registre des présences</h1>

<nav class="nav secondaryCustomNav">
    <a class="nav-link" asp-action="GetRegisters" asp-controller="Register">Effectif</a>
    <span class="nav-link">Planning</span>
</nav>

<hr />
<div class="customBreadcrumb">
    @Html.ActionLink("DashBoard", "Index", "Admin") |
    @Html.ActionLink("Ajouter", "SetStatus", "RegisterPlanning")
</div>

<div class="adapt75">
    <input type="hidden" value="@TempData["Alert"]" id="alert" />
    <div class="d-flex align-items-baseline">
        @await Html.PartialAsync("_RegisterFilter")
        @*<partial name="_RegisterFilter" />*@
        <form asp-action="Index" method="get" class="d-flex lastFlex">
            <input type="text" name="SearchString" value="@ViewData["nameFilter"]" size="12" style="margin-right:0.5rem;" />
            <button type="submit" class="btn-custom"><span class="material-icons">search</span></button>
        </form>
    </div>
</div>

<!-- Modal placeholder -->
<div id="modal-placeholder">
</div>

<div id="registerPlanningListing" class="adapt75">

    @if (Model.Count() > 0)
    {
        @foreach (RegisterPlanningVM item in Model)
        {
            <table id="@String.Format("registerPlanningListing{0}", item.Id)" class="table custom-table-bordered table-condensed registersTable tableCustomLayout">
                <thead>
                    <tr>
                        <th colspan="2">
                            <a href="#" title="Edit Product">@item.LName @item.FName</a>
                            <div class="companyTh">
                                @Html.DisplayFor(modelItem => item.CompanyName) (@Html.DisplayFor(modelItem => item.StatusName))
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <strong>@Html.DisplayNameFor(modelItem => item.TimeIn): </strong>@Html.DisplayFor(modelItem => item.TimeIn)<br />
                        </td>

                        <td style="text-align: right" ;>
                            @if (item.TimeOut == null)
                            {
                                @Html.DisplayFor(modelItem => item.TimeOut)<br />
                            }
                            else
                            {
                                <strong>Sortie: </strong>@Html.DisplayFor(modelItem => item.TimeOut)<br />
                            }
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <strong>@Html.DisplayNameFor(modelItem => item.Planned): </strong>@item.Planned.BoolToHtmlString("Oui", "Non")<br />
                        </td>
                        <td style="text-align: right" ;>
                            <strong>@Html.DisplayNameFor(modelItem => item.State): </strong>@Html.DisplayFor(modelItem => item.State)<br />
                        </td>
                    </tr>
                    @if (item.Planned == true && item.State != "Présent(e)")
                    {
                        <tr>
                            <td colspan="2" class="tr-background">
                                <a asp-controller="RegisterPlanning" asp-action="Edit" asp-route-id="@item.Id" data-toggle="ajax-modal-EditRegisterPlanning" data-target="#EditRegisterPlanningModal" data-url="@Url.Action("Edit", "RegisterPlanning", new { id = item.Id })">Modifier</a>
                            </td>
                        </tr>

                    }
                    else if (item.Planned == false && item.State == "Présent(e)")
                    {
                        <tr>
                            <td colspan="2" class="tr-background">
                                @*<a href="#" id="registerPlanningSetPlanned">Marquer comme plannifié</a>*@
                                <a id="registerPlanningSetPlanned" asp-controller="RegisterPlanning" asp-action="SetAsPlanned" asp-route-id="@item.Id">Marquer comme plannifié</a>
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        }
    }
    else
    {
        <p class="emptyContent">Aucune personne ne se trouve dans le registre pour la période souhaitée.</p>
    }
</div>

@section Scripts {
    <script>

        $(document).ready(function () {

            // Time Filtering
            let filterSelector = $("#registerFilter");
            let filterVal = filterSelector.val();

            let searchSelector = $("input[name='SearchString']");
            let searchVal = searchSelector.val();

            filterSelector.change(function () {
                filterVal = filterSelector.val();
                searchVal = searchSelector.val();

                $.ajax({
                    url: "/RegisterPlanning/GetRegisters",
                    type: "GET",
                    data: { sortOrder: filterVal, searchString: searchVal },
                    success: function (result) {
                        var htmlResult = $("#registerPlanningListing", result);
                        $("#registerPlanningListing").replaceWith(htmlResult);
                        $("#registerFilter").find("option[value=" + filterVal + "]").attr('selected', true);
                    }
                }); // End AJax Call
            }); // End Change

            // Search filter
            let submit = $("button[type='submit']");

            submit.on('click', (function (e) {
                e.preventDefault();

                filterVal = filterSelector.val();
                searchVal = searchSelector.val();

                $.ajax({
                    url: "/RegisterPlanning/GetRegisters",
                    type: "GET",
                    data: { sortOrder: filterVal, searchString: searchVal },
                    success: function (result) {
                        $("body").html(result);
                        $("#registerFilter").find("option[value=" + filterVal + "]").attr('selected', true);
                    }
                }); // End AJax Call
            })); // End Submit


            // Modify RegisterPlanning open modal
            $(document).on("click", "a[data-toggle='ajax-modal-EditRegisterPlanning']", function (e) {
                e.preventDefault();

                var url = $(this).data('url');

                // Load partial modal
                $.ajax({
                    url: url,
                    type: "GET",
                    //headers: { "RequestVerificationToken": modalToken },
                    success: function (result) {
                        $('#modal-placeholder').html(result);
                        $('#modal-placeholder > .modal').modal('show');
                    }
                });
            });

            // Save registerPlanning modifications 
            $(document).on("click", "button[data-save='save-edit-registerplanning']", function (e) {
                e.preventDefault();

                let parent = $(this).closest(".modal-dialog");
                let id = parent.find("#Id").val();
                let url = parent.find("form").attr('action');
                let dataToSend = parent.find("form").serialize();

                let toReplace = $(document).find("table#registerPlanningListing" + id);

                $.ajax({
                    url: url,
                    type: "POST",
                    data: dataToSend,
                    //headers: { "RequestVerificationToken": modalToken },
                    success: function (result) {

                        // If form modal partial view is returned, display error
                        var errorModal = $(result).filter('#EditRegisterPlanningModal');  

                        if (errorModal.length) {
                            var newBody = $('.modal-body', result);
                            $('#modal-placeholder').find('.modal-body').replaceWith(newBody);
                        }
                        else {
                            // Hide Modal form
                            $('#modal-placeholder').find('.modal').modal('hide');
                            toReplace.replaceWith(result);
                        }
                    }
                });
            })
            

            // Set as planned
            $(document).on("click", "#registerPlanningSetPlanned", function (e) {
                e.preventDefault();

                var url = $(this).attr('href');

                // Load partial modal
                $.ajax({
                    url: url,
                    type: "GET",
                    //headers: { "RequestVerificationToken": modalToken },
                    success: function (result) {

                        // If form modal partial view is returned, display error
                        var errorModal = $(result).filter('.modal');  
                        
                        if (errorModal.length) {                            
                            $('#modal-placeholder').append(result);
                            $('#modal-placeholder > .modal').modal('show');
                        }
                        else {                            
                            let urlSplit = url.split('/');
                            let id = urlSplit[3];
                            let toReplace = $(document).find("table#registerPlanningListing" + id);
                            toReplace.replaceWith(result);
                        }
                    }
                });
            });


        });
    </script>
}


RegisterLLAT/WebApp/Views/RegisterPlanning/Summary.cshtml
@model List<WebApp.Models.RegisterPlanningViewModels.RegisterPlanningVM>

@{
    ViewData["Title"] = "Summary";
}

<h1>Registre des présences</h1>
<h2>Ajout: récapitutaltif</h2>
<hr />

<div class="customBreadcrumb">
    @Html.ActionLink("DashBoard", "Index", "Admin")
    @*@Html.ActionLink("Retour à la liste", "GetRegisterPlanning", "RegisterPlanning")*@
</div>

<p>
    Voici le récapitulatif du/des ajout(s) au planning:<br />
    @if (ViewBag.Updates > 0 && ViewBag.Inserts > 0)
    {
        @:- @ViewBag.Updates registre(s) mis à jour et @ViewBag.Inserts ajoutés<br />
    }
    else if (ViewBag.Inserts > 0)
    {
        @:- @ViewBag.Inserts ajoutés<br />
    }
    else
    {
        @:- @ViewBag.Updates registre(s) mis à jour<br />
    }

    @if (ViewBag.Duplicates > 0)
    {
        @:- @ViewBag.Duplicates registre(s) n'a/n'ont pas été modifié(s) car déjà existant en base de données
    }
</p>

<div class="adapt75">
    <table class="table custom-table-bordered table-condensed registersTable tableCustomLayout">
        <thead>
            <tr>
                <th colspan="2">
                    <span style="color:#0366d6;">@ViewBag.LName @ViewBag.FName</span>
                    <div class="companyTh">
                        @ViewBag.Company (@ViewBag.Status)
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <strong>@Html.DisplayNameFor(modelItem => item.TimeIn): </strong>@Html.DisplayFor(modelItem => item.TimeIn)
                    </td>
                    <td style="text-align:right" ;>
                        <strong>@Html.DisplayNameFor(modelItem => item.TimeOut): </strong>@Html.DisplayFor(modelItem => item.TimeOut)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


<a class="btn btn-primary" asp-action="Index" asp-controller="Admin">Terminer</a>

RegisterLLAT/WebApp/Views/RegisterPlanning/_RegisterPlanningItem.cshtml
@model WebApp.Models.RegisterPlanningViewModels.RegisterPlanningVM

<table class="table custom-table-bordered table-condensed registersTable tableCustomLayout">
    <thead>
        <tr>
            <th colspan="2">
                <a href="#" title="Edit Product">@Model.LName @Model.FName</a>
                <div class="companyTh">
                    @Html.DisplayFor(modelItem => Model.CompanyName) (@Html.DisplayFor(modelItem => Model.StatusName))
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <strong>@Html.DisplayNameFor(modelItem => Model.TimeIn): </strong>@Html.DisplayFor(modelItem => Model.TimeIn)<br />
            </td>

            <td style="text-align: right" ;>
                @if (Model.TimeOut == null)
                {
                    @Html.DisplayFor(modelItem => Model.TimeOut)<br />
                }
                else
                {
                    <strong>Sortie: </strong>@Html.DisplayFor(modelItem => Model.TimeOut)<br />
                }
            </td>
        </tr>

        <tr>
            <td>
                <strong>@Html.DisplayNameFor(modelItem => Model.Planned): </strong>@Model.Planned.BoolToHtmlString("Oui", "Non")<br />
            </td>
            <td style="text-align: right" ;>
                <strong>@Html.DisplayNameFor(modelItem => Model.State): </strong>@Html.DisplayFor(modelItem => Model.State)<br />
            </td>
        </tr>
        @if (Model.Planned == true && Model.State != "Présent(e)")
        {
            <tr>
                <td colspan="2" class="tr-background">
                    <a asp-action="Edit" asp-route-id="@Model.Id" data-toggle="ajax-modal-EditRegisterPlanning" data-target="#EditRegisterPlanningModal" data-url="@Url.Action("Edit", "RegisterPlanning", new { id = Model.Id })">Modifier</a>
                </td>
            </tr>

        }
        else if (Model.Planned == false && Model.State == "Présent(e)")
        {
            <tr>
                <td colspan="2" class="tr-background">
                    <a href="#" id="registerPlanningSetPlanned">Marquer comme plannifié</a>
                </td>
            </tr>

        }
    </tbody>
</table>