RegisterLLAT/WebApp/Models/Company.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
	public class Company
	{
		[Key]
		public int Id { get; set; }

		public string CompanyName { get; set; }

		public bool Deleted { get; set; }

		public int CompanyStatusId { get; set; }

		public string StatusName { get; set; }

		public int TestId { get; set; }

		public string Title { get; set; }

		public int? AdministratorId { get; set; }

		public string AdminLName { get; set; }

		public string AdminFName { get; set; }
	}
}

RegisterLLAT/WebApp/Models/CompanyViewModels/CompanyForm.cs
using DAL.Services;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using WebApp.AppTools;
using DALE = DAL.Entities;
using WebApp.AppTools.Attributes;

namespace WebApp.Models.CompanyViewModels
{
	public class CompanyForm
	{
		[Key]
		public int Id { get; set; }

		[Required(ErrorMessage = "Le nom de la société est requis")]
		[DisplayName("Nom")]
		public string CompanyName { get; set; }

		[Required(ErrorMessage = "Le statut de la société est requis")]
		[DisplayName("Statut")]
		public int CompanyStatusId { get; set; }

		private List<CompanyStatus> _companyStatuses;

		public List<CompanyStatus> CompanyStatuses
		{
			get
			{
				if (_companyStatuses == null)
				{
					CompanyStatusService serv = new CompanyStatusService();
					_companyStatuses = serv.GetAll().Select(c => c.DalToCompanyStatusApp()).ToList();
				}
				return _companyStatuses;
			}
			set { _companyStatuses = value; }
		}

		[DisplayName("Statut")]
		public string StatusName { get; set; }

		[DisplayName("Archivée")]
		public bool Deleted { get; set; } = false;

		[DisplayName("Encodeur")]
		public int? AdministratorId { get; set; }

		public string AdminLName { get; set; }

		public string AdminFName { get; set; }

		private string _adminName;

		[DisplayName("Encodeur")]
		public string AdminName
		{
			get
			{
				if (AdminLName == null && AdminFName == null)
				{
					_adminName = "un utilisateur à l'enregistrement";
				}
				else
				{
					_adminName = AdminLName.ToUpper() + " " + AdminFName;
				}
				return _adminName;
			}
			set { _adminName = value; }
		}

		[DisplayName("Test")]
		public int TestId { get; set; } = 1;

		[DisplayName("Test")]
		public string TestName { get; set; }

		private List<DALE.Test> _tests;

		public List<DALE.Test> Tests
		{
			get 
			{
				if (_tests == null)
				{
					TestService testService = new TestService();
					_tests = testService.GetAll().ToList();
				}
				return _tests; 
			}
			set { _tests = value; }
		}

		private List<DALE.Person> _persons;

		public List<DALE.Person> Persons
		{
			get 
			{
				if (_persons == null)
				{
					PersonService personService = new PersonService();
					if (Id == 1)
					{
						_persons = personService.GetPersonsByCompany(Id).OrderBy(p => p.DepartmentName).ThenBy(p => p.LName).ToList();
					}
					else
					{
						_persons = personService.GetPersonsByCompany(Id).OrderBy(p => p.LName).ToList();
					}										
				}
				return _persons;
			}
			set { _persons = value; }
		}

	}
}

RegisterLLAT/WebApp/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DAL.Services;
using DALE = DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using WebApp.AppTools;
using WebApp.Models;
using WebApp.Models.CompanyViewModels;
using System.Net.NetworkInformation;
using Microsoft.AspNetCore.Authorization;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Super Admin, Full Admin, HR Admin")]
    //[Authorize("SuperAdmin")] 
    public class CompanyController : Controller
    {
        public IActionResult Index()
        {
            CompanyService serv = new CompanyService();

            IEnumerable<CompanyForm> companies = serv.GetAll().OrderBy(c => c.CompanyName).Select(c => c.DalToCompanyForm()).ToList();

            // Prepare ViewBag for modal display in view in case of redirectToAction from Edit, Activate, Deactivate
            if (TempData["title"] != null && TempData["message"] != null)
            {
                ViewBag.ModalTitle = TempData["title"];
                TempData.Remove("title");

                ViewBag.ModalMessage = TempData["message"];
                TempData.Remove("message");
            }

            // Prepare filter dropdown list
            CompanyStatusService companyStatusService = new CompanyStatusService();
            ViewBag.StatusDropDown = companyStatusService.GetAll();

            return View(companies);
        }

        [HttpPost]
        public IActionResult Filter(int statusId, string search, bool isNew = false)
        {
            CompanyService service = new CompanyService();
            IEnumerable<CompanyForm> compagnies;

            if (String.IsNullOrWhiteSpace(search))
            {
                // If the user makes no choice
                if (statusId == 0)
                {
                    compagnies = service.GetAll().Select(q => q.DalToCompanyForm()).ToList();
                }
                else
                {
                    compagnies = service.GetAll(statusId).Select(q => q.DalToCompanyForm()).ToList();
                }
            }
            else
            {
                // If the user makes no choice
                if (statusId == 0)
				{
                    compagnies = service.GetAll(search).Select(q => q.DalToCompanyForm()).ToList();
                }
				else
				{
                    compagnies = service.GetAll(search, statusId).Select(q => q.DalToCompanyForm()).ToList();
                }                
            }

            // Filter companies added while user registration (administratorId is null)
			if (isNew == true)
			{
                compagnies = compagnies.Where(c => c.AdministratorId == null);
			}
            return PartialView("_CompanyFilter", compagnies);
        }

        [HttpGet]
        public IActionResult Create()
        {
            CompanyForm form = new CompanyForm();
            return View(form);
        }

        [HttpPost]
        public IActionResult Create(CompanyForm form)
        {
            // Client side validation
            if (!ModelState.IsValid)
            {
                return View(form);
            }

            // Check that status and test are valid and Prevent duplicate entries in the DB
            ViewBag.Error = ValidateCompany(form);            
            
            // If validation is OK
            if (ViewBag.Error == null)
			{
                CompanyService serv = new CompanyService();
                DALE.Company company = new DALE.Company()
                {
                    CompanyName = form.CompanyName,
                    CompanyStatusId = form.CompanyStatusId,
                    TestId = form.TestId,
                };

				try
				{
                    company.Id = serv.Insert(company);
                }
				catch (Exception e)
				{
					throw e;
				}

                TempData["title"] = "Création d'une société";
                TempData["message"] = "La société a été ajoutée avec succès.";

                return RedirectToAction("Details", new { id = company.Id });
            }     
            return View(form);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            // Check that company exist in DB
            DALE.Company companyExist = ControllerMethods.CheckCompanyExist(id);
            if (companyExist == null)
            {
                TempData["title"] = "Erreur";
                TempData["message"] = "La société que vous souhaitez consulter n'existe pas.";
                return RedirectToAction("Index");
            }

            // In case of redirection from edit or create prepare modal display
            if (TempData["title"] != null && TempData["message"] != null)
            {
                ViewBag.ModalTitle = TempData["title"];
                TempData.Remove("title");

                ViewBag.ModalMessage = TempData["message"];
                TempData.Remove("message");
            }

            CompanyForm companyForm = companyExist.DalToCompanyForm();

            TestService testService = new TestService();
            companyForm.TestName = testService.Get(companyForm.TestId).Title;

            return View(companyForm);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Check that company exist in DB
            DALE.Company companyExist = ControllerMethods.CheckCompanyExist(id);
			if (companyExist == null)
			{
                TempData["title"] = "Erreur";
                TempData["message"] = "La société que vous souhaitez éditer n'existe pas.";
                return RedirectToAction("Index");
            }
            
            CompanyForm companyForm = companyExist.DalToCompanyForm();

            return View(companyForm);
        }

        [HttpPost]
        public IActionResult Edit(CompanyForm company)
        {
            // Client side validation
            if (!ModelState.IsValid)
            {
                return View(company);
            }

            // Check that company exist in DB
            DALE.Company companyExist = ControllerMethods.CheckCompanyExist(company.Id);
            
            if (companyExist == null)
            {
                TempData["title"] = "Erreur";
                TempData["message"] = "La société que vous souhaitez éditer n'existe pas.";
                return RedirectToAction("Index");
            }

            // Check that status and testId are valid + avoid duplicate names for company in DB
            ViewBag.Error = ValidateCompany(company);

            // Return view in case of error
			if (ViewBag.Error != null)
			{
                return View(company);
            }

            // Update company if all the tests are valid
            CompanyService companyService = new CompanyService();            
            DALE.Company companyToEdit = company.CompanyFormToDal();

			try
			{
                companyService.Update(companyToEdit);
            }
			catch (Exception e)
			{
				throw e;
			}

            TempData["title"] = "Edition de la société";
            TempData["message"] = "La société a été éditée avec succès.";
            
            return RedirectToAction("Details", new { id = companyToEdit.Id } );
        }

        /// <summary>
        /// Alert user that softdeleting a company will prevent its employees from accessing register and test
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult SoftDelete()
        {
            return PartialView("_SoftDelete");
        }

        /// <summary>
        /// Alert user that hardDeleting a company will hardDelete its employees along with their linked registers, registersPlanning, tests.
        /// The departments linked to the company will also be removed.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult HardDelete()
        {
            return PartialView("_HardDelete");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            // Check that company exist in DB
            DALE.Company companyExist = ControllerMethods.CheckCompanyExist(id);

            if (companyExist == null)
            {
                TempData["title"] = "Erreur";
                TempData["message"] = "La société que vous souhaitez supprimer n'existe pas.";
                return RedirectToAction("Index");
            }

            // Delete company
            CompanyService service = new CompanyService();
			try
			{
                service.Delete(id);
            }
			catch (Exception e)
			{
				throw e;
			}

            TempData["title"] = "Suppression de la société";
            TempData["message"] = "La société a été supprimée avec succès.";

            return RedirectToAction("Index");
        }


        /// <summary>
        /// Check if the name of the company does not already exist in DB
        /// </summary>
        /// <param name="company"></param>
        /// <returns></returns>
        [NonAction]
        private string AvoidDuplicateCompanyName(CompanyForm company)
        {
            string result = null;

            CompanyService serv = new CompanyService();
            IEnumerable<Company> companies = serv.GetAll().Select(c => c.DalToCompanyApp());
            var isInDB = companies.Where(c => c.CompanyName.Equals(company.CompanyName, StringComparison.OrdinalIgnoreCase) && c.Id != company.Id)
                .Select(c => c)
                .FirstOrDefault();

            if (isInDB != null)
            {
                result = "Le nom de cette société existe déjà; deux sociétés avec le même noms ne peuvent être enregistrées.";

RegisterLLAT/WebApp/Views/Company/Create.cshtml
@model WebApp.Models.CompanyViewModels.CompanyForm

@{
    ViewData["Title"] = "Create";
}

<h1>Société</h1>
<h2>Ajouter</h2>
<hr />

<div class="customBreadcrumb">
    @Html.ActionLink("DashBoard", "Index", "Admin") |
    <a asp-controller="Company" asp-action="Index">Liste des sociétés</a>
</div>


<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CompanyStatusId" class="control-label"></label>
                <select asp-items="@(new SelectList(Model.CompanyStatuses, "Id", "StatusName"))" asp-for="CompanyStatusId">
                    <option value="0">-- Sélectionnez un status --</option>
                </select>
                <span asp-validation-for="CompanyStatusId" class="d-block text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TestId" class="control-label"></label>
                <select asp-items="@(new SelectList(Model.Tests, "Id", "Title", Model.TestId))" asp-for="TestId">
                    <option value="0">-- Sélectionnez un test --</option>
                </select>
                <span asp-validation-for="TestId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Valider" class="btn btn-primary" />
            </div>
        </form>
        @if (ViewBag.Error != null)
        {
            <div>
                <p class="text-danger">Une erreur est survenue : @ViewBag.Error</p>
            </div>
        }
    </div>
</div>


@section Scripts {
    <script>
        // # TODO : Add custom validation for custom data annotation
        // https://www.devtrends.co.uk/blog/the-complete-guide-to-validation-in-asp.net-mvc-3-part-1
        // https://jqueryvalidation.org/jQuery.validator.addMethod/


        // AutoComplete for the company name
        // Suggestions will allow the user to potentially chose an existing company
        // If the user makes a choice, the Id of the company and the companyStatus will be inserted in hidden input fields
        // The persistence logic will reside in the controller
        $("#CompanyName").autocomplete({
            minLength: 3,
            source: function (request, response) {
                $.ajax({
                    url: "/Register/AutoComplete",
                    type: "POST",
                    dataType: "json",
                    data: { Prefix: request.term.toLowerCase() },
                    success: function (data) {

                        var array = data.error ? [] : $.map(data, function (m) {
                            return {
                                label: m.companyName,
                                value: m.id,
                                status: m.companyStatusId,
                            };
                        });
                        response(array);
                    },
                });
            },
            select: function (event, ui) {
                $("#CompanyName").val(ui.item.label);
                $("#IdAutoComplete").val(ui.item.value);
                $("#CompanyStatusId").val(ui.item.status);
                return false;
            }
        })

    </script>
}

RegisterLLAT/WebApp/Views/Company/Details.cshtml
@model WebApp.Models.CompanyViewModels.CompanyForm

@{
    List<Department> departments = ViewBag.Departments as List<Department>;
}

@{
    ViewData["Title"] = "Details";
}

<h1>Société</h1>
<h2>Détail: @Model.CompanyName</h2>
<hr />

<div class="customBreadcrumb">
    @Html.ActionLink("DashBoard", "Index", "Admin") |
    <a asp-action="Index">Liste des sociétés</a> |
    @Html.ActionLink("Editer", "Edit", new { Id = Model.Id }) |
    <a asp-controller="Person" asp-action="Create" asp-route-companyId="@Model.Id">Ajouter un employé</a>
</div>

<!-- Modal placeholder -->
<div id="modal-placeholder">
</div>

<div id="editCompanyContainer">
    <input type="hidden" asp-for="Id" />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>
        <dd class="col-sm-10">
            @Model.Deleted.BoolToHtmlString("Oui", "Non")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TestName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TestName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdminName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdminName)
        </dd>
    </dl>
</div>

@if (@Model.Persons.Count() > 0)
{
    <p><strong>Liste des employés (@Model.Persons.Count())</strong></p>

    if (Model.Id == 1)
    {
        <ul>
            @foreach (var item in Model.Persons)
            {
                <li>@Html.DisplayFor(m => item.DepartmentName) : @Html.DisplayFor(m => item.LName) @Html.DisplayFor(m => item.FName)</li>
            }
        </ul>
    }
    else
    {
        <ul>
            @foreach (var item in Model.Persons)
            {
                <li>@Html.DisplayFor(m => item.LName) @Html.DisplayFor(m => item.FName)</li>
            }
        </ul>
    }
}
else
{
    <p><strong>Liste des employés</strong></p>
    <p>Aucun employé n'est présent dans cette société. <a asp-controller="Person" asp-action="Create" asp-route-companyId="@Model.Id">Veuillez en ajouter</a></p>
}


@if (ViewBag.ModalTitle != null && ViewBag.ModalMessage != null)
{
    <div class="d-none" id="viewBagModal">
        <p class="modalTitle">@ViewBag.ModalTitle</p>
        <p class="modalMessage">@ViewBag.ModalMessage</p>
    </div>
}

@section Scripts{
    <script>
        $(document).ready(function () {

            // Display modal after redirection from Controller (works with ViewBag.ModalTitle & ViewBag.ModalMessage)
            // After redirection from edit or create       
            let viewBag = $("#viewBagModal");
            if (viewBag.length) {

                let title = $("p.modalTitle").html();
                let message = $("p.modalMessage").html();
                DisplayModal(title, message);
            }
        });
    </script>
}

RegisterLLAT/WebApp/Views/Company/Index.cshtml
@model IEnumerable<WebApp.Models.CompanyViewModels.CompanyForm>
@using Microsoft.AspNetCore.Http.Extensions

@{
    ViewData["Title"] = "Index";
    //var url = Context.Request.GetDisplayUrl();
}

<h1>Sociétés</h1>
<h2>Listing</h2>
<hr />

<div class="customBreadcrumb">
    @Html.ActionLink("DashBoard", "Index", "Admin") |
    <a asp-controller="Company" asp-action="Create" method="get">Ajouter</a>
</div>

<!-- Modal placeholder -->
<div id="modal-placeholder">
</div>

<div class="adapt75 topButton">
    <div class="d-flex align-items-baseline">

        <div class="form-group" style="margin-right: 1rem;">
            <label for="CompanyStatusId" class="control-label"></label>
            <select id="StatusDropDown" name="StatusDropDown" asp-items="@(new SelectList(@ViewBag.StatusDropDown, "Id", "StatusName"))">
                <option value="0">-- Filtre par statut --</option>
            </select>
        </div>

        <div>
            <label for="IsNew">
                New
                <input type="checkbox" name="IsNew" />
            </label>
        </div>

        <form asp-action="Filter" method="post" class="d-flex lastFlex">
            <input type="text" name="SearchString" size="24" style="margin-right:0.5rem;" />
            <button id="SearchStringBtn" type="submit" class="btn-custom"><span class="material-icons">search</span></button>
        </form>

    </div>
</div>

<div class="adapt75" id="companyListContainer">
    @if (Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            //string identity = "user" + item.Id;

            <table id="@item.Id" class="table table-bordered table-condensed table-striped tableCustomLayout">
                <tbody>
                    <tr>
                        <th>
                            <a asp-controller="Company" asp-action="Details" asp-route-id="@item.Id" title="Profil de la société">@item.CompanyName</a>
                            <div class="thSideBySide">
                                @Html.DisplayFor(modelItem => item.StatusName)
                            </div>
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <strong>@Html.DisplayNameFor(modelItem => item.Deleted): </strong> @item.Deleted.BoolToHtmlString("Oui", "Non")<br />
                            <strong>@Html.DisplayNameFor(modelItem => item.TestName): </strong> @item.TestName<br />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            @Html.ActionLink("Editer", "Edit", new { id = item.Id })
                        </td>
                    </tr>
                </tbody>
            </table>
        }
    }
    else
    {
        <p>Le filtrage n'a donné aucun résultat.</p>
    }
</div>

@if (ViewBag.ModalTitle != null && ViewBag.ModalMessage != null)
{
    <div class="d-none" id="viewBagModal">
        <p class="modalTitle">@ViewBag.ModalTitle</p>
        <p class="modalMessage">@ViewBag.ModalMessage</p>
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {

            // Display modal after redirection from Controller (works with ViewBag.ModalTitle & ViewBag.ModalMessage)
            // If trying to get details from a non existing company       
            let viewBag = $("#viewBagModal");
            if (viewBag.length) {

                let title = $("p.modalTitle").html();
                let message = $("p.modalMessage").html();
                DisplayModal(title, message);
            }

            // Filter variables for ListFilter js function
            let controller = "Company";
            let container = $("#companyListContainer")

            // Change event on checkbox "new company"
            $("input[name='IsNew']").on("change", function (e) {
                ListFilter(controller, container); 
            });

            // Change event on selected status
            $("#StatusDropDown").change(function () {
                ListFilter(controller, container);
            }); // End change on dropdown

            // Filter by string
            $("#SearchStringBtn").click(function (e) {
                e.preventDefault();
                ListFilter(controller, container);
            });
        });
    </script>
}

RegisterLLAT/WebApp/Views/Company/_CompanyFilter.cshtml
@model IEnumerable<WebApp.Models.CompanyViewModels.CompanyForm>

@if (Model.Count() > 0)
{
    @foreach (var item in Model)
    {
        //string identity = "user" + item.Id;

        <table id="@item.Id" class="table table-bordered table-condensed table-striped tableCustomLayout">
            <tbody>
                <tr>
                    <th>
                        <a asp-controller="Company" asp-action="Details" asp-route-id="@item.Id" title="Profil de la société">@item.CompanyName</a>
                        <div class="thSideBySide">
                            @Html.DisplayFor(modelItem => item.StatusName)
                        </div>
                    </th>
                </tr>
                <tr>
                    <td>
                        <strong>@Html.DisplayNameFor(modelItem => item.Deleted): </strong> @item.Deleted.BoolToHtmlString("Oui", "Non")<br />
                        <strong>@Html.DisplayNameFor(modelItem => item.TestName): </strong> @item.TestName<br />
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        @Html.ActionLink("Editer", "Edit", new { id = item.Id })
                        @*@if (item.Deleted == true)
                        {
                            @Html.ActionLink("Restaurer", "Restore", new { id = item.Id })
                        }
                        else
                        {
                            @Html.ActionLink("Archiver", "SoftDelete", new { id = item.Id })
                        }*@
                    </td>
                </tr>
            </tbody>
        </table>
    }
}
else
{
    <p>Le filtrage n'a donné aucun résultat.</p>
}

RegisterLLAT/WebApp/Views/Company/_HardDelete.cshtml


<!-- Modal -->
<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Suppression d'une société: avertissement</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Vous êtes sur le point de supprimer une société.</p>
                <p>Si vous validez le formulaire, le ou les employés de cette société ainsi que les données qui lui ou leur sont associées (registre, tests) seront également définitivement supprimés.</p>
                <p>Cliquez sur "Suppimer" pour valider le formulaire ou sur "Annuler" pour revenir à l'édition.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-save="companyHardDelete-modal">Supprimer</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

RegisterLLAT/WebApp/Views/Company/_SoftDelete.cshtml


<!-- Modal -->
<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Archivage d'une société: avertissement</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Vous êtes sur le point d'archiver une société.</p>
                <p>Si vous validez le formulaire, le ou les employés de cette société ne pourront plus s'inscrire dans le registre et passer les tests.</p>
                <p>Cliquez sur "Archiver" pour valider le formulaire ou sur "Annuler" pour revenir à l'édition.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-save="companySoftDelete-modal">Archiver</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>