RegisterLLAT/WebApp/Models/Register.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebApp.AppTools;

namespace WebApp.Models
{
	public class Register
	{
		[Key]
		public int Id { get; set; }

		public DateTime TimeIn { get; set; }

		public DateTime? TimeOut { get; set; }

		public string Mistake { get; set; }

		public int PersonId { get; set; }

		public string LName { get; set; }

		public string FName { get; set; }

		public string CompanyName { get; set; }

		public string StatusName { get; set; }

		public int? PersonVisited { get; set; }

		public string VisitedLName { get; set; }

		public string VisitedFName { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterPlanningViewModels/SetCompany.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace WebApp.Models.RegisterPlanningViewModels
{
	public class SetCompany 
	{
		public int MyProperty { get ; set ; }
	}
}

RegisterLLAT/WebApp/Models/RegisterPlanningViewModels/SetStatus.cs
using DAL.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using WebApp.AppTools;

namespace WebApp.Models.RegisterPlanningViewModels
{
	public class SetStatus
	{
		[Key]
		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }

		private IEnumerable<CompanyStatus> _companyStatuses;

		public IEnumerable<CompanyStatus> CompanyStatus
		{
			get 
			{
				if (_companyStatuses == null)
				{
					CompanyStatusService service = new CompanyStatusService();
					_companyStatuses = service.GetAll().Select(cs => cs.DalToCompanyStatusApp());
				}
				return _companyStatuses; 
			}
			set { _companyStatuses = value; }
		}

		// public IEnumerable<CompanyStatus> CompanyStatus { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetCompany.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using WebApp.AppTools.Attributes;

namespace WebApp.Models.RegisterViewModels
{
	public class SetCompany
	{
		[Key]
		[Display(Name = "Nom de la société")]
		[EmptyOrPositive(ErrorMessage = "Ce champ doit être un nombre positif ou sans valeur")]
		public int? Id { get; set; }

		public List<SelectListItem> Options { get; set; } // TODO : potential useless

		public List<Company> Companies { get; set; }

		[Display(Name = "Indiquez le nom de la société")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le nom de la société est requis")]
		public string Name { get; set; }

		public int IdAutoComplete { get; set; }

		[Display(Name = "Département")]
		[EmptyOrPositive(ErrorMessage = "Ce champ doit être un nombre positif ou sans valeur")]
		public int? DepartmentId { get; set; } // TODO : potential useless

		public List<Department> Departments { get; set; } 

		[Display(Name = "Nom du département")]
		[RequiredIfOtherFieldIsZero("DepartmentId", ErrorMessage = "Le nom du département est requis")]
		public string DepartmentName { get; set; } // TODO : potential useless

		public int CompanyStatusId { get; set; } // TODO : potential useless
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetPerson.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebApp.AppTools.Attributes;

namespace WebApp.Models.RegisterViewModels
{
	public class SetPerson
	{
		[Key]
		[Display(Name = "Vos nom et prénom")]
		public int? Id { get; set; }

		public List<SelectListItem> OptionsPersons { get; set; }

		public List<PersonListVM> Persons { get; set; }

		[Display(Name = "Nom de famille")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le nom de famille est requis")]
		public string LName { get; set; }

		[Display(Name = "Prénom")]
		[RequiredIfOtherFieldIsZero("Id", ErrorMessage = "Le prénom est requis")]
		public string FName { get; set; }

		public DateTime? DateBegin { get; set; }

		public DateTime? DateEnd { get; set; }

		[Display(Name = "Personne visitée")]
		public int? PersonVisitedId { get; set; }

		public List<SelectListItem> OptionsPVisited { get; set; }

		public List<PersonListVM> PersonsVisited { get; set; }
	}
}

RegisterLLAT/WebApp/Models/RegisterViewModels/SetStatus.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace WebApp.Models.RegisterViewModels
{
	public class SetStatus
	{
		[Key]
		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }

		public IEnumerable<CompanyStatus> CompanyStatus { get; set; }
	}
}

RegisterLLAT/WebApp/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using DAL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using WebApp.AppTools;
using WebApp.Models;
using WebApp.Models.PersonTestViewModels;
using WebApp.Models.TestViewModels;
using DALE = DAL.Entities;

namespace WebApp.Controllers
{
	[Authorize(Roles = "Super Admin, Full Admin, Prevention Admin")]
	public class TestController : Controller
	{
		[HttpGet]
		public IActionResult Index()
		{
			TestService service = new TestService();

			IEnumerable<TestVM> tests = service.GetAll().Select(t => t.DalToTestVM()).ToList();

			// Prepare ViewBag for modal display in view in case of redirectToAction from Edit, Activate, Deactivate
			if (TempData["title"] != null && TempData["message"] != null)
			{
				ViewBag.ModalTitle = TempData["title"];
				TempData.Remove("title");

				ViewBag.ModalMessage = TempData["message"];
				TempData.Remove("message");
			}

			return View("Index", tests);
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			// Check that test exists
			DALE.Test testExist = CheckTestExist(id);

			if (testExist == null)
			{
				TempData["title"] = "Erreur";
				TempData["message"] = "Le test que vous souhaitez éditer n'existe pas";
				return RedirectToAction("Index");
			}

			TestVM test = testExist.DalToTestVM();

			return View(test);
		}

		[HttpPost]
		public IActionResult Edit(TestVM test)
		{
			// Model validation
			if (!ModelState.IsValid)
			{
				return View(test);
			}

			// Server side validation
			ViewBag.Error = ValidateTest(test);

			if (ViewBag.Error != null)
			{
				return View(test);
			}

			// Prepare modal display	
			TempData["title"] = "Edition du test";
			TempData["message"] = "Edition réalisée avec succès.";

			// Check if question can be activated	
			if (test.IsActive)
			{
				string activated = TestCanBeActivated(test);

				if (activated != null)
				{
					TempData["message"] += " Cependant, " + activated;
					test.IsActive = false;
				}				
			}

			// Update Test
			TestService service = new TestService();			
			try
			{
				service.Update(test.TestVMToDal());
			}
			catch (Exception e)
			{
				throw e;
			}			

			return RedirectToAction("Details", new { id = test.Id });
		}

		[HttpGet]
		public IActionResult Details(int id)
		{
			// Check that test exists
			DALE.Test testExist = CheckTestExist(id);

			if (testExist == null)
			{
				// Prepare modal display	
				TempData["title"] = "Erreur";
				TempData["message"] = "Ce test n'existe pas.";
				return RedirectToAction("Index");
			}

			// Prepare ViewBag for modal display in view in case of redirectToAction from Create or Edit
			if (TempData["title"] != null && TempData["message"] != null)
			{
				ViewBag.ModalTitle = TempData["title"];
				TempData.Remove("title");
				
				ViewBag.ModalMessage = TempData["message"];
				TempData.Remove("message");
			}

			TestVM test = testExist.DalToTestVM();

			return View(test);
		}

		[HttpGet]
		public IActionResult Create()
		{
			TestVM test = new TestVM();
			return View(test);
		}

		[HttpPost]
		public IActionResult Create(TestVM test)
		{
			// Model validation
			if (!ModelState.IsValid)
			{
				return View(test);
			}

			// Server side validation
			ViewBag.Error = ValidateTest(test);

			if (ViewBag.Error != null)
			{
				return View(test);
			}

			// Validation Ok, insert test into DB
			TestService service = new TestService();
			try
			{
				test.Id = service.Insert(test.TestVMToDal());
			}
			catch (Exception e)
			{
				throw e;
			}

			// Prepare modal display
			TempData["title"] = "Création du test";
			TempData["message"] = "Test créé avec succès.";

			return RedirectToAction("Details", new { id = test.Id });
		}

		[HttpGet]
		public IActionResult VisualiseVideo(string videoUrl)
		{
			ViewBag.Url = videoUrl;
			return PartialView("_VisualiseVideoModal");
		}

		[HttpPost]
		public IActionResult Activate(int id)
		{
			TestService service = new TestService();

			TestVM test = service.Get(id).DalToTestVM();

			string activate = TestCanBeActivated(test);

			if (activate != null)
			{
				ViewBag.ModalTitle = "Activation du test";
				ViewBag.ModalMessage = "Malheureusement " + activate;
				return PartialView("_DisplayModal");
			}

			// Validation OK, activate test and update it
			test.IsActive = true;

			try
			{
				service.Update(test.TestVMToDal());
			}
			catch (Exception e)
			{
				throw e;
			}

			//test = service.Get(id).DalToTestVM();

			return PartialView("_TestTable", test);
		}

		[HttpPost]
		public IActionResult Deactivate(int id)
		{
			TestService service = new TestService();

			DALE.Test test = service.Get(id);

			test.IsActive = false;

			try
			{
				service.Update(test);
			}
			catch (Exception e)
			{
				throw e;
			}

			TestVM testVM = service.Get(id).DalToTestVM();

			return PartialView("_TestTable", testVM);
		}

		/// <summary>
		/// Alert user that hardDeleting a test will hardDelete the test and all the employees's result corresponding to that test.
		/// All companies linked to this test will be automatically linked with the default test.
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public IActionResult HardDelete()
		{
			return PartialView("_HardDelete");
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			// Check that Test existh
			DALE.Test testExist = CheckTestExist(id);

			TempData["title"] = "Suppression d'un test";

			if (testExist == null)
			{
				// If test does not exist prepare message
				TempData["message"] = "Ce test n'existe pas.";
			}
			else
			{
				TestService service = new TestService();
				try
				{
					service.Delete(id);
				}
				catch (Exception e)
				{
					throw e;
				}

				// If deletion is OK prepare message
				TempData["message"] = "La suppression du test a été réalisée avec succès";
			}
			return RedirectToAction("Index");
		}

		[AllowAnonymous]
		[HttpGet]
		public IActionResult TakeTest()
		{
			User user = GetUser();

			PersonTestService service = new PersonTestService();
			PersonTestVM personTest; 

			try
			{
				personTest = service.Get(user.PersonTestId).DalToPersonTestVM(); 
			}
			catch (Exception e)
			{
				throw e;
			}

			// Extract video ID
			string Url = personTest.TestVM.VideoURL;
			string[] Id = Url.Split('/');
			ViewBag.VideoURL = Id[3];

			return View(personTest);			
		}

		[AllowAnonymous]
		[HttpGet]
		public IActionResult Questions()
		{
			User user = GetUser();

			PersonTestService service = new PersonTestService();
			PersonTestVM personTest = new PersonTestVM();

			try
			{
				personTest = service.Get(user.PersonTestId).DalToPersonTestVM();
			}
			catch (Exception e)
			{
				throw e;
			}

			return View(personTest);
		}

		[AllowAnonymous]
		[HttpPost]
		public IActionResult Questions(IFormCollection form)
		{
			PersonTestVM Test = new PersonTestVM();
			Test.PersonAnswers = new List<AnswersVM>();
			
			// Get user's answers for questionIds
			foreach (var key in form.Keys)
			{
				if (key.Contains("question"))
				{
					int id = int.Parse(key.Replace("question", ""));
					int answerId = int.Parse(form["question" + id]);
					Test.PersonAnswers.Add(new AnswersVM() { QuestionId = id, QcmItemId = answerId });	
				}
			}

			// Get user's test result
			int numberQuestion = Test.PersonAnswers.Count();
			float questionWeigh = 10 / (float)numberQuestion;
			float result = 0;

			// Calculate result and prepare test summary
			QuestionQcmItemService questionQcmItemService = new QuestionQcmItemService();

			// Get qmcItems for each question
			foreach (var userAnswer in Test.PersonAnswers)
			{
				DALE.QuestionQcmItem check = questionQcmItemService.GetByQuestionIdQcmItemId(userAnswer.QuestionId, userAnswer.QcmItemId);
				if (check.QcmItemIsAnswer == true)
				{
					result += questionWeigh;
				}
				userAnswer.Item = check.QcmItemItem;
			}

			// Update user's test as he has just completed a test and set Person IsInOrder field 
			User user = GetUser();
			PersonTestService service = new PersonTestService();
			Test.Id = user.PersonTestId;
			Test.PersonId = user.Id;
			Test.TestId = int.Parse(form["TestId"]);
			Test.Result = result;
			Test.TakeDate = DateTime.Now;
			try
			{
				service.Update(Test.PersonTestVMToDal());
			}
			catch (Exception e)
			{
				throw e;
			}

			// Display final result to user
			if (Test.Result >= Test.TestVM.TestSettingsTreshold)
			{
				ViewBag.TestSuccess = true;
			}
			else
			{
				ViewBag.TestSuccess = false;
			}

			RemoveUser();
			return View("Results", Test); 
		}

		[NonAction]
		private User GetUser()
		{
			var session = HttpContext.Session.GetComplexData<User>("user");

			if (session == null)
			{
				User user = new User();
				HttpContext.Session.SetComplexData("user", user);
			}
			return (User)HttpContext.Session.GetComplexData<User>("user");
		}

		/// <summary>
		/// Reset user cookie data to null
		/// </summary>
		/// <param name="user"></param>
		[NonAction]
		private void ResetUser(User user)
		{
			user.CompanyId = null;
			user.CompanyName = null;
			user.DepartmentId = null;
			user.DepartmentName = null;
			user.PersonVisited = null;
			user.Id = 0;
			HttpContext.Session.SetComplexData("user", user);
		}

		[NonAction]
		private void RemoveUser()
		{
			HttpContext.Session.Clear();
		}

		/// <summary>

RegisterLLAT/WebApp/Views/Register/AddRegisterPlanningCompany.cshtml
@model WebApp.Models.RegisterViewModels.SetCompany

@{
    ViewData["Title"] = "AddRegisterPlanningCompany";
}

@*<partial name="_AddRegisterWizardMenu" />*@
@await Html.PartialAsync("_AddRegisterWizardMenu")

<div class="col-md-6">

    @if (Model.CompanyStatusId == 1)
    {
        <p>Dans quel département de la SNCB travaille cet employé?</p>
    }
    else
    {
        <p>Pour quelle société travaille cet employé?</p>
    }

    <form class="addRegisterPlanningWizard" asp-action="AddRegisterPlanningCompany" method="post">

        <input type="hidden" asp-for="CompanyStatusId" />

        @* if the user is an intern (SNCB) *@
        @if (Model.CompanyStatusId == 1)
        {
            if (Model.Departments.Count() > 0)
            {
                @* Give companyId the value "1" which is the SNCB Id *@
                <div class="form-group" id="addRegisterPlanning-company">

                    <input type="hidden" asp-for="Id" value="1" />

                    <select asp-items="@(new SelectList(Model.Departments, "Id", "Name", Model.DepartmentId))" asp-for="DepartmentId">
                        <option value="">-- Sélectionnez un département --</option>
                    </select>
                </div>

                @*Input text for department's other name*@
                <div class="form-group d-none" id="setDepartmentNameOther">
                    <label asp-for="DepartmentName" class="control-label"></label>
                    <input asp-for="DepartmentName" class="form-control" />
                    <span asp-validation-for="DepartmentName" class="text-danger"></span>
                </div>
            }
        }
        else
        {
            if (Model.Companies != null)
            {
                <div class="form-group">
                    <select asp-items="@(new SelectList(Model.Companies, "Id", "CompanyName", Model.Id))" asp-for="Id">
                        <option value="">-- Sélectionnez une société --</option>
                    </select>
                </div>

                if (Model.Departments != null)
                {
                    @*DropDown List for department*@
                    <div class="form-group" id="setCompanyDepartment">
                        <p>Dans quel département?</p>
                        <select asp-items="@(new SelectList(Model.Departments, "Id", "Name", Model.DepartmentId))" asp-for="DepartmentId">
                            <option value="">-- Sélectionnez un département --</option>
                        </select>
                    </div>
                }
                else
                {
                    @*DropDown List for department*@
                    <div class="form-group d-none" id="setCompanyDepartment">
                        <p>Dans quel département?</p>
                        <select name="DepartmentId" id="DepartmentId">
                            <option value="">-- Sélectionnez un département --</option>
                        </select>
                    </div>
                }

                @*Input text for company's other name*@
                <div class="form-group d-none" id="setCompanyNameOther">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                @*Input text for department's other name*@
                <div class="form-group d-none" id="setDepartmentNameOther">
                    <label asp-for="DepartmentName" class="control-label"></label>
                    <input asp-for="DepartmentName" class="form-control" />
                    <span asp-validation-for="DepartmentName" class="text-danger"></span>
                </div>
            }
            else
            {
                @*Input text for company's other name*@
                <div class="form-group" id="setCompanyNameOther">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            }
        }

        @if (ViewBag.Error != null)
        {
            <div id="viewBagError">
                <p class="text-danger">Une erreur est survenue : @ViewBag.Error</p>
            </div>
        }

        <div class="form-group addRegisterPlanningWizardBtnNext">
            <input type="submit" name="prevBtn" value="Précédent" class="btn btn-primary" />
            <input type="submit" name="nextBtn" value="Suivant" class="btn btn-primary" />
        </div>

    </form>

</div>


@section Scripts {
    <script>

        // Add custom Client Validation (custom data annotations)
        $.validator.addMethod("required-if-otherfield-is-zero", function (value, element, params) {
            var otherfield = $("#" + params.otherfield).val();

            if (otherfield === "0" & isNullOrWhitespace(value)) {
                return false;
            }
            else {
                return true;
            }
        });

        $.validator.unobtrusive.adapters.add("required-if-otherfield-is-zero", ["otherfield"], function (options) {
            options.rules["required-if-otherfield-is-zero"] =
            {
                otherfield: options.params['otherfield']
            };
            options.messages["required-if-otherfield-is-zero"] = options.message;

        });

        $(document).ready(function () {

            // Function
            function hideDepartmentOnChange() {
                $("select#DepartmentId").change(function () {
                    departmentOtherName.find(":input").val("");
                    hideElements(departmentOtherName);
                    depId = $("#DepartmentId").val();
                    if (depId === "0") {
                        showElements(departmentOtherName);
                    }
                    else {
                        hideElements(departmentOtherName);
                    }
                });
            }

            // Modify tabs menu
            let tabStatus = $("#addRegisterMenuItemStatus span");
            let tabPerson = $("#addRegisterMenuItemPerson span");
            let tabCompany = $("#addRegisterMenuItemCompany span");

            disableActiveTab(tabStatus, tabPerson);
            enableActiveTab(tabCompany);

            // FadeOut ViewBag + display form as it was before error
            if ($("#viewBagError").length) {

                //if ($("#DepartmentId").val() === "0") {
                //    if ($("#setDepartmentNameOther").hasClass("d-none")) {
                //        $("#setDepartmentNameOther").removeClass("d-none")
                //    }
                //}

                // In case of view returned with error
                //$("select#DepartmentId").change(function () {
                //    console.log("departement id change");

                //    if (!departmentOtherName.hasClass('d-none')) {
                //        departmentOtherName.addClass('d-none')
                //    }

                //    depId = $("#DepartmentId").val();

                //    if (depId === "0") {
                //        departmentOtherName.removeClass('d-none');;
                //    }
                //    else {
                //        departmentOtherName.addClass('d-none');
                //    }
                //});
                // End of change event on department

                fadeOutCustom($("#viewBagError"), 10000)
            }

            // Manage show and hide inputs according to dropdowns values
            let department = $("#setCompanyDepartment");
            let depId = $("#DepartmentId").val();

            let departmentOtherName = $("#setDepartmentNameOther");

            let compOtherName = $("#setCompanyNameOther");
            let companyId = $("#Id").val();

            // The user is part of SNCB
            if (companyId === "1") {

                hideDepartmentOnChange();
            }
            else {
                $("#Id").change(function () {

                    $("#Name").val("");

                    // Clear html elements
                    hideElements(compOtherName, department, departmentOtherName);

                    companyId = $("#Id").val();

                    if (companyId === "0") {
                        showElements(compOtherName);
                    }

                    if (companyId > 1) {

                        // Check wether the company has departments
                        $.ajax({
                            url: "/Register/GetDepartmentsByCompany",
                            data: { companyId: companyId },
                            type: "POST",
                            headers: { "RequestVerificationToken": $("input[name='__RequestVerificationToken']").val() },
                            success: function (result) {
                                if (result != 0) {

                                    // If departments exists
                                    $("#DepartmentId").empty();
                                    $("#DepartmentId").append("<option value=''>-- Sélectionnez un département --</option>");
                                    department.removeClass('d-none');

                                    $.each(result, function (index, row) {
                                        $("#DepartmentId").append("<option value='" + row.id + "'>" + row.name + "</option>");
                                    })
                                }
                                else {
                                    $("#DepartmentId").val("");
                                }
                            },
                            dataType: "json",
                        }); // End of ajax call

                        hideDepartmentOnChange();

                    } // End of if

                }); // End of change event on company

                // For navigation (Next & Previous) purposes
                hideDepartmentOnChange();
            }

        }); // End document ready

    </script>
}

RegisterLLAT/WebApp/Views/Register/AddRegisterPlanningStatus.cshtml
@model WebApp.Models.RegisterViewModels.SetStatus

@{
    ViewData["Title"] = "AddRegisterPlanningStatus";
}

@await Html.PartialAsync("_AddRegisterWizardMenu")
@*<partial name="_AddRegisterWizardMenu" />*@

<div class="col-md-6">
    <p>Quel est le statut de l'employé?</p>

    <form class="addRegisterPlanningWizard" asp-action="AddRegisterPlanningStatus" method="post">

        <div class="form-group">
            <select asp-items="@(new SelectList(Model.CompanyStatus, "Id", "StatusName", Model.Id))" asp-for="Id">
                <option value="0">-- Sélectionnez un statut --</option>
            </select>
        </div>

        @if (ViewBag.Error != null)
        {
            <div id="viewBagError">
                <p class="text-danger">Une erreur est survenue : @ViewBag.Error</p>
            </div>
        }

        <div class="form-group addRegisterPlanningWizardBtnNext">
            <input type="submit" name="nextBtn" value="Suivant" class="btn btn-primary" />
        </div>

    </form>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {

            // FadeOut ViewBag + display form as it was before error
            if ($("#viewBagError").length) {
                fadeOutCustom($("#viewBagError"), 10000)
            }

            // Modify tabs menu
            let tabStatus = $("#addRegisterMenuItemStatus span");
            let tabCompany = $("#addRegisterMenuItemCompany span");

            disableActiveTab(tabCompany);
            enableActiveTab(tabStatus);

        }); // End document ready

    </script>
}



RegisterLLAT/WebApp/Views/Register/GetDepartmentsByCompany.cshtml
@model WebApp.Models.Department

@{
    ViewData["Title"] = "GetDepartmentsByCompany";
}

<h1>GetDepartmentsByCompany</h1>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

RegisterLLAT/WebApp/Views/Register/Index.cshtml

@*@{
    ViewData["Title"] = "Index";
}

<h1>Registre des présences</h1>
<hr class="withoutBreadCrumb" />

@Html.ActionLink("Signaler son arrivée", "SetStatus", "Register",
    new { isCheckingOut = "false" },
    new { @class = "btn btn-primary" })

@Html.ActionLink("Signaler son départ", "SetStatus", "Register",
    new { isCheckingOut = "true" },
    new { @class = "btn btn-primary" })*@

@{
    ViewData["Title"] = "Index";
}

<h1>Registre des présences</h1>
<h2>Enregistrement</h2>
<hr />
<p>A votre arrivée sur le site, cliquez sur "Signaler son arrivée". A la sortie, n'oubliez pas de signer en cliquant sur "Signaler son départ."</p>

<p>Si vous quittez le site et que vous avez oublié de signer à votre arrivée, cliquez sur "Signalez son départ".</p>

<form class="d-inline-block" asp-controller="Register" asp-action="Index" method="post">
    <input type="hidden" name="isCheckingOut" value="false" />
    <input class="btn btn-primary" type="submit" value="Signaler son arrivée" />
</form>

<form class="d-inline-block" asp-controller="Register" asp-action="Index" method="post">
    <input type="hidden" name="isCheckingOut" value="true" />
    <input class="btn btn-primary" type="submit" value="Signaler son départ" />
</form>

RegisterLLAT/WebApp/Views/Register/RegisterSummary.cshtml

@{
    ViewData["Title"] = "RegisterSummary";
}

<h1>Registre des présences</h1>
<h2>Enregistrement terminé</h2>
<hr />


<p>Merci d'avoir signé le registre.</p>

@if (ViewBag.IsCheckInOut == false)
{
    <p>N'oubliez pas de signer à nouveau lors de votre sortie.</p>
}
else
{
    if (Model.Mistake != null)
    {
        <p>Nous constatons que vous avez oublié de vous enregistrer à votre arrivée. Soyez attentif-ve lors de votre prochaine visite.</p>
    }
}

@if (ViewBag.TestActive == true)
{
    <p>Nous souhaiterions à présent vérifier votre maîtrise des règles de sécurité.</p>
    <p>Merci de cliquer sur "Passer le test".</p>   
    <a class="btn btn-primary" asp-action="TakeTest" asp-controller="Test">Passer le test</a>
}
else
{
    <a class="btn btn-primary" asp-action="Index" asp-controller="Home">Terminer</a>
}



